version: "2"
services:
    client:
        container_name: yolo-client
        restart: unless-stopped
        build: client/
        ports:
            - "3000:3000"
        
        networks:
            - yolo_webapp
    
    backend:
        container_name: yolo-backend
        restart: unless-stopped
        build: backend/
        ports:
            - "5000:5000"
        depends_on:
            - mongodb
        networks:
            - yolo_webapp
    
    mongodb:
        image: mongo
        container_name: mongodb
        ports:
            - 27017:27017
        volumes:
            - ./data:/data/db
        networks:
            - yolo_webapp

networks:
    yolo_webapp:
        driver: bridge