version: "2"
services:
    client:
        restart: always
        build: client/
        ports:
            - "3000:3000"
        links:
            - backend
        networks:
            - yolo_webapp
    
    backend:
        restart: always
        build: backend/
        ports:
            -"5000:5000"
        depends_on:
            - mongodb
        networks:
            - yolo_webapp
    
    mongo:
        image: mongo
        container_name: mongodb
        ports:
            - 27017:27017
        volumes:
            - ./data:/data/db
        networks:
            - yolo_webapp
        

    

networks:
    yolo_webapp:
        driver: bridge